pipeline { 
    agent any 
    // options {
    //     skipStagesAfterUnstable()
    // }
    stages {
        stage('Build Docker Image') { 
            steps { 
                sh 'cd DockerWatch && docker build . -t dockerwatch' 
            }
        }
    }
}

